[package]
name = "tss-macros-tests"
authors.workspace = true
description.workspace = true
edition.workspace = true
homepage.workspace = true
keywords.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
tree-sitter = "0.26.7"
tree-sitter-rust = "0.24.2"
tss-macros = {path = "../tss-macros"}
